#include <stddef.h>

#include "crazypod_route_registry.h"

#define FEATURE_ROUTE(route_, feature_) \
    [route_] = { \
        route_, CRAZYPOD_ROUTE_OWNER_FEATURE, \
        &features[feature_], CRAZYPOD_ROUTE_FLAG_NONE \
    }
#define FEATURE_ROUTE_FLAGS(route_, feature_, flags_) \
    [route_] = { \
        route_, CRAZYPOD_ROUTE_OWNER_FEATURE, \
        &features[feature_], flags_ \
    }
#define SHELL_ROUTE(route_) \
    [route_] = { \
        route_, CRAZYPOD_ROUTE_OWNER_SHELL, NULL, \
        CRAZYPOD_ROUTE_FLAG_NONE \
    }

static const struct crazypod_feature features[CRAZYPOD_FEATURE_COUNT] = {
    [CRAZYPOD_FEATURE_MUSIC] = {
        CRAZYPOD_FEATURE_MUSIC, "music"
    },
    [CRAZYPOD_FEATURE_NOW_PLAYING] = {
        CRAZYPOD_FEATURE_NOW_PLAYING, "now_playing"
    },
    [CRAZYPOD_FEATURE_BOOKS] = {
        CRAZYPOD_FEATURE_BOOKS, "books"
    },
    [CRAZYPOD_FEATURE_NOTES] = {
        CRAZYPOD_FEATURE_NOTES, "notes"
    },
    [CRAZYPOD_FEATURE_PHOTOS] = {
        CRAZYPOD_FEATURE_PHOTOS, "photos"
    },
    [CRAZYPOD_FEATURE_ORGANIZER] = {
        CRAZYPOD_FEATURE_ORGANIZER, "organizer"
    },
    [CRAZYPOD_FEATURE_CUSTOMIZE] = {
        CRAZYPOD_FEATURE_CUSTOMIZE, "customize"
    },
    [CRAZYPOD_FEATURE_SETTINGS] = {
        CRAZYPOD_FEATURE_SETTINGS, "settings"
    },
    [CRAZYPOD_FEATURE_MINIAPPS] = {
        CRAZYPOD_FEATURE_MINIAPPS, "miniapps"
    },
};

const struct crazypod_feature *crazypod_feature_get(
    enum crazypod_feature_id id)
{
    if((unsigned int)id >= CRAZYPOD_FEATURE_COUNT)
        return NULL;
    return &features[id];
}

static const struct crazypod_route_descriptor
routes[CRAZYPOD_ROUTE_COUNT] = {
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_MENU, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW |
        CRAZYPOD_ROUTE_FLAG_SKEUOMORPHIC_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ALBUM_FLOW, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_SOLID_BLACK),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ALL, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_PLAYLISTS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_PLAYLIST_SONGS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ARTISTS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ARTIST_SONGS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ALBUMS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_ALBUM_SONGS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_SONGS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE(MUSIC_ROUTE_SEARCH, CRAZYPOD_FEATURE_MUSIC),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_SEARCH_RESULTS, CRAZYPOD_FEATURE_MUSIC,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE_FLAGS(
        MUSIC_ROUTE_QUEUE, CRAZYPOD_FEATURE_NOW_PLAYING,
        CRAZYPOD_ROUTE_FLAG_PREVIEW),
    FEATURE_ROUTE(
        MUSIC_ROUTE_NOW_PLAYING, CRAZYPOD_FEATURE_NOW_PLAYING),
    FEATURE_ROUTE_FLAGS(
        PHOTOS_ROUTE_MENU, CRAZYPOD_FEATURE_PHOTOS,
        CRAZYPOD_ROUTE_FLAG_SKEUOMORPHIC_PREVIEW),
    FEATURE_ROUTE(PHOTOS_ROUTE_LIBRARY, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_VIDEOS, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_FAVORITES, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_DELETE_MENU, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_DELETE_PHOTOS, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_DELETE_VIDEOS, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(
        PHOTOS_ROUTE_DELETE_PHOTO_CONFIRM, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(
        PHOTOS_ROUTE_DELETE_VIDEO_CONFIRM, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(PHOTOS_ROUTE_DETAIL, CRAZYPOD_FEATURE_PHOTOS),
    FEATURE_ROUTE(SETTINGS_ROUTE_MENU, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_SOUND, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_EQ_STUDIO, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_DISPLAY, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_PLAYBACK, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_POWER, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(SETTINGS_ROUTE_CONTROLS, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(
        SETTINGS_ROUTE_MAIN_MENU, CRAZYPOD_FEATURE_SETTINGS),
    FEATURE_ROUTE(
        SETTINGS_ROUTE_MAIN_MENU_ACTIONS, CRAZYPOD_FEATURE_SETTINGS),
    SHELL_ROUTE(EXTRAS_ROUTE_MENU),
    FEATURE_ROUTE_FLAGS(
        NOTES_ROUTE_MENU, CRAZYPOD_FEATURE_NOTES,
        CRAZYPOD_ROUTE_FLAG_SKEUOMORPHIC_PREVIEW),
    FEATURE_ROUTE(NOTES_ROUTE_COMPOSER, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(NOTES_ROUTE_EXIT_ACTIONS, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_DISCARD_CONFIRM, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(NOTES_ROUTE_SEARCH, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_SEARCH_RESULTS, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(NOTES_ROUTE_READER, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(NOTES_ROUTE_ACTIONS, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(NOTES_ROUTE_DELETED, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_DELETED_ACTIONS, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_DELETE_CONFIRM, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_PERMANENT_CONFIRM, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE(
        NOTES_ROUTE_EMPTY_TRASH_CONFIRM, CRAZYPOD_FEATURE_NOTES),
    FEATURE_ROUTE_FLAGS(
        BOOKS_ROUTE_MENU, CRAZYPOD_FEATURE_BOOKS,
        CRAZYPOD_ROUTE_FLAG_SKEUOMORPHIC_PREVIEW),
    FEATURE_ROUTE(BOOKS_ROUTE_RECENTS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_LIBRARY, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_FAVORITES, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE_FLAGS(
        BOOKS_ROUTE_READER, CRAZYPOD_FEATURE_BOOKS,
        CRAZYPOD_ROUTE_FLAG_BOOK_READER),
    FEATURE_ROUTE(BOOKS_ROUTE_ACTIONS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_CHAPTERS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_BOOKMARKS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(
        BOOKS_ROUTE_DELETE_CONFIRM, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_STATS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(
        BOOKS_ROUTE_READING_SETTINGS, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(BOOKS_ROUTE_INFO, CRAZYPOD_FEATURE_BOOKS),
    FEATURE_ROUTE(PODCASTS_ROUTE_MENU, CRAZYPOD_FEATURE_MUSIC),
    FEATURE_ROUTE(UTILITIES_ROUTE_MENU, CRAZYPOD_FEATURE_MINIAPPS),
    FEATURE_ROUTE_FLAGS(
        MINIAPP_ROUTE_VIEW, CRAZYPOD_FEATURE_MINIAPPS,
        CRAZYPOD_ROUTE_FLAG_SOLID_BLACK),
    FEATURE_ROUTE(CLOCK_ROUTE_MENU, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(
        CLOCK_ROUTE_SLEEP_TIMER, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        CLOCK_ROUTE_VIEW, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN |
        CRAZYPOD_ROUTE_FLAG_DARK_STATUS),
    FEATURE_ROUTE_FLAGS(
        STOPWATCH_ROUTE_VIEW, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN |
        CRAZYPOD_ROUTE_FLAG_DARK_STATUS),
    FEATURE_ROUTE(WORKOUT_ROUTE_MENU, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(WORKOUT_ROUTE_TYPES, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        WORKOUT_ROUTE_READY, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE_FLAGS(
        WORKOUT_ROUTE_ACTIVE, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE(
        WORKOUT_ROUTE_FINISH_CONFIRM, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(WORKOUT_ROUTE_HISTORY, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        WORKOUT_ROUTE_SUMMARY, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE_FLAGS(
        WORKOUT_ROUTE_DETAIL, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE(
        WORKOUT_ROUTE_DELETE_CONFIRM, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(CALENDAR_ROUTE_MENU, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(CALENDAR_ROUTE_TODAY, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(
        CALENDAR_ROUTE_UPCOMING, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        CALENDAR_ROUTE_MONTH, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN |
        CRAZYPOD_ROUTE_FLAG_DARK_STATUS),
    FEATURE_ROUTE_FLAGS(
        CALENDAR_ROUTE_DAY_EVENTS, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN |
        CRAZYPOD_ROUTE_FLAG_DARK_STATUS),
    FEATURE_ROUTE(CALENDAR_ROUTE_EDITOR, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(
        CALENDAR_ROUTE_TITLE_EDITOR, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        CALENDAR_ROUTE_DETAIL, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE(CALENDAR_ROUTE_ACTIONS, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(
        CALENDAR_ROUTE_DELETE_CONFIRM, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE(CONTACTS_ROUTE_LIST, CRAZYPOD_FEATURE_ORGANIZER),
    FEATURE_ROUTE_FLAGS(
        CONTACTS_ROUTE_DETAIL, CRAZYPOD_FEATURE_ORGANIZER,
        CRAZYPOD_ROUTE_FLAG_FULLSCREEN),
    FEATURE_ROUTE(DIY_ROUTE_MENU, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(DIY_ROUTE_PRESETS, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_PRESET_LIBRARY, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_PRESET_ACTIONS, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(DIY_ROUTE_PRESET_EDIT, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_PRESET_RENAME, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(DIY_ROUTE_ICONS, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(DIY_ROUTE_DETAILS, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(DIY_ROUTE_CHOICES, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_BACKGROUNDS, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_BACKGROUND_CHOICES, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_WALLPAPER_FILES, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE_FLAGS(
        DIY_ROUTE_WALLPAPER_CROP, CRAZYPOD_FEATURE_CUSTOMIZE,
        CRAZYPOD_ROUTE_FLAG_SOLID_BLACK),
    FEATURE_ROUTE(DIY_ROUTE_LAYOUT, CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_NOW_PLAYING_THEMES,
        CRAZYPOD_FEATURE_CUSTOMIZE),
    FEATURE_ROUTE(
        DIY_ROUTE_HEADPHONE_POPUP,
        CRAZYPOD_FEATURE_CUSTOMIZE),
};

const struct crazypod_route_descriptor *
crazypod_route_registry_get(enum crazypod_route route)
{
    if((unsigned int)route >= CRAZYPOD_ROUTE_COUNT)
        return NULL;
    return &routes[route];
}

const struct crazypod_feature *
crazypod_route_registry_feature(enum crazypod_route route)
{
    const struct crazypod_route_descriptor *descriptor =
        crazypod_route_registry_get(route);

    return descriptor != NULL &&
           descriptor->owner == CRAZYPOD_ROUTE_OWNER_FEATURE
        ? descriptor->feature : NULL;
}

bool crazypod_route_registry_is_shell(enum crazypod_route route)
{
    const struct crazypod_route_descriptor *descriptor =
        crazypod_route_registry_get(route);

    return descriptor != NULL &&
           descriptor->owner == CRAZYPOD_ROUTE_OWNER_SHELL;
}

bool crazypod_route_registry_has_flag(
    enum crazypod_route route, enum crazypod_route_flag flag)
{
    const struct crazypod_route_descriptor *descriptor =
        crazypod_route_registry_get(route);

    return descriptor != NULL &&
           (descriptor->flags & (unsigned int)flag) != 0;
}

bool crazypod_route_registry_validate(void)
{
    enum crazypod_route route;

    for(route = 0; route < CRAZYPOD_ROUTE_COUNT; ++route) {
        const struct crazypod_route_descriptor *descriptor =
            &routes[route];

        if(descriptor->route != route)
            return false;
        if(descriptor->owner == CRAZYPOD_ROUTE_OWNER_FEATURE) {
            if(descriptor->feature == NULL ||
               (unsigned int)descriptor->feature->id >=
                   CRAZYPOD_FEATURE_COUNT)
                return false;
        }
        else if(descriptor->owner != CRAZYPOD_ROUTE_OWNER_SHELL ||
                descriptor->feature != NULL)
            return false;
    }
    return true;
}
