#ifndef CRAZYPOD_UI_ROUTES_H
#define CRAZYPOD_UI_ROUTES_H

#include <stdbool.h>

enum crazypod_route {
    MUSIC_ROUTE_MENU,
    MUSIC_ROUTE_ALBUM_FLOW,
    MUSIC_ROUTE_ALL,
    MUSIC_ROUTE_PLAYLISTS,
    MUSIC_ROUTE_PLAYLIST_SONGS,
    MUSIC_ROUTE_ARTISTS,
    MUSIC_ROUTE_ARTIST_SONGS,
    MUSIC_ROUTE_ALBUMS,
    MUSIC_ROUTE_ALBUM_SONGS,
    MUSIC_ROUTE_SONGS,
    MUSIC_ROUTE_SEARCH,
    MUSIC_ROUTE_SEARCH_RESULTS,
    MUSIC_ROUTE_QUEUE,
    MUSIC_ROUTE_NOW_PLAYING,
    PHOTOS_ROUTE_MENU,
    PHOTOS_ROUTE_LIBRARY,
    PHOTOS_ROUTE_VIDEOS,
    PHOTOS_ROUTE_FAVORITES,
    PHOTOS_ROUTE_DELETE_MENU,
    PHOTOS_ROUTE_DELETE_PHOTOS,
    PHOTOS_ROUTE_DELETE_VIDEOS,
    PHOTOS_ROUTE_DELETE_PHOTO_CONFIRM,
    PHOTOS_ROUTE_DELETE_VIDEO_CONFIRM,
    PHOTOS_ROUTE_DETAIL,
    SETTINGS_ROUTE_MENU,
    SETTINGS_ROUTE_SOUND,
    SETTINGS_ROUTE_EQ_STUDIO,
    SETTINGS_ROUTE_DISPLAY,
    SETTINGS_ROUTE_DATE_TIME,
    SETTINGS_ROUTE_PLAYBACK,
    SETTINGS_ROUTE_POWER,
    SETTINGS_ROUTE_CONTROLS,
    SETTINGS_ROUTE_MAIN_MENU,
    SETTINGS_ROUTE_MAIN_MENU_ACTIONS,
    EXTRAS_ROUTE_MENU,
    NOTES_ROUTE_MENU,
    NOTES_ROUTE_COMPOSER,
    NOTES_ROUTE_EXIT_ACTIONS,
    NOTES_ROUTE_DISCARD_CONFIRM,
    NOTES_ROUTE_SEARCH,
    NOTES_ROUTE_SEARCH_RESULTS,
    NOTES_ROUTE_READER,
    NOTES_ROUTE_ACTIONS,
    NOTES_ROUTE_DELETED,
    NOTES_ROUTE_DELETED_ACTIONS,
    NOTES_ROUTE_DELETE_CONFIRM,
    NOTES_ROUTE_PERMANENT_CONFIRM,
    NOTES_ROUTE_EMPTY_TRASH_CONFIRM,
    BOOKS_ROUTE_MENU,
    BOOKS_ROUTE_RECENTS,
    BOOKS_ROUTE_LIBRARY,
    BOOKS_ROUTE_FAVORITES,
    BOOKS_ROUTE_READER,
    BOOKS_ROUTE_ACTIONS,
    BOOKS_ROUTE_CHAPTERS,
    BOOKS_ROUTE_BOOKMARKS,
    BOOKS_ROUTE_DELETE_CONFIRM,
    BOOKS_ROUTE_STATS,
    BOOKS_ROUTE_READING_SETTINGS,
    BOOKS_ROUTE_INFO,
    PODCASTS_ROUTE_MENU,
    UTILITIES_ROUTE_MENU,
    MINIAPP_ROUTE_VIEW,
    CLOCK_ROUTE_MENU,
    CLOCK_ROUTE_SLEEP_TIMER,
    CLOCK_ROUTE_VIEW,
    STOPWATCH_ROUTE_VIEW,
    WORKOUT_ROUTE_MENU,
    WORKOUT_ROUTE_TYPES,
    WORKOUT_ROUTE_READY,
    WORKOUT_ROUTE_ACTIVE,
    WORKOUT_ROUTE_FINISH_CONFIRM,
    WORKOUT_ROUTE_HISTORY,
    WORKOUT_ROUTE_SUMMARY,
    WORKOUT_ROUTE_DETAIL,
    WORKOUT_ROUTE_DELETE_CONFIRM,
    CALENDAR_ROUTE_MENU,
    CALENDAR_ROUTE_TODAY,
    CALENDAR_ROUTE_UPCOMING,
    CALENDAR_ROUTE_MONTH,
    CALENDAR_ROUTE_DAY_EVENTS,
    CALENDAR_ROUTE_EDITOR,
    CALENDAR_ROUTE_TITLE_EDITOR,
    CALENDAR_ROUTE_DETAIL,
    CALENDAR_ROUTE_ACTIONS,
    CALENDAR_ROUTE_DELETE_CONFIRM,
    CONTACTS_ROUTE_LIST,
    CONTACTS_ROUTE_DETAIL,
    DIY_ROUTE_MENU,
    DIY_ROUTE_PRESETS,
    DIY_ROUTE_PRESET_LIBRARY,
    DIY_ROUTE_PRESET_ACTIONS,
    DIY_ROUTE_PRESET_EDIT,
    DIY_ROUTE_PRESET_RENAME,
    DIY_ROUTE_ICONS,
    DIY_ROUTE_DETAILS,
    DIY_ROUTE_CHOICES,
    DIY_ROUTE_BACKGROUNDS,
    DIY_ROUTE_BACKGROUND_CHOICES,
    DIY_ROUTE_WALLPAPER_FILES,
    DIY_ROUTE_WALLPAPER_CROP,
    DIY_ROUTE_LAYOUT,
    DIY_ROUTE_NOW_PLAYING_THEMES,
    DIY_ROUTE_HEADPHONE_POPUP,
    GAMEBOY_ROUTE_LIBRARY,
};

#define CRAZYPOD_ROUTE_COUNT ((int)GAMEBOY_ROUTE_LIBRARY + 1)

struct route_state {
    enum crazypod_route route;
    int selected;
    int group;
};

void crazypod_ui_routes_clear(void);
void crazypod_ui_routes_reset(
    enum crazypod_route route, int group, int selected);
int crazypod_ui_routes_depth(void);
struct route_state *crazypod_ui_routes_current(void);
struct route_state *crazypod_ui_routes_at(int index);
bool crazypod_ui_routes_push(
    enum crazypod_route route, int group, int selected);
bool crazypod_ui_routes_pop(void);
void crazypod_ui_routes_truncate(int depth);

#endif
