/* Generated by tools/generate-crazypod-l10n.py. Do not edit. */
#ifndef CRAZYPOD_MINIAPP_L10N_H
#define CRAZYPOD_MINIAPP_L10N_H

struct cp_l10n_entry {
    const char *source;
    const char *values[CP_LANGUAGE_COUNT];
};

static const struct cp_l10n_entry cp_l10n_entries[] = {
    { "Error", { "Error", "错误", "錯誤", "エラー", "오류", "Fehler", "Erreur", "Error", "Erro" } },
    { "Cannot divide by zero", { "Cannot divide by zero", "不能除以零", "不能除以零", "0では割れません", "0으로 나눌 수 없음", "Division durch null nicht möglich", "Division par zéro impossible", "No se puede dividir entre cero", "Não é possível dividir por zero" } },
    { "Result out of range", { "Result out of range", "结果超出范围", "结果超出范围", "結果が範囲外です", "결과가 범위를 벗어남", "Ergebnis außerhalb des Bereichs", "Résultat hors limites", "Resultado fuera de rango", "Resultado fora do intervalo" } },
    { " OF ", { " OF ", " / ", " / ", " / ", " / ", " VON ", " SUR ", " DE ", " DE " } },
    { " MIN", { " MIN", " 分钟", " 分鐘", "分", "분", " MIN.", " MIN", " MIN", " MIN" } },
    { " ROUNDS", { " ROUNDS", " 轮", " 回合", "ラウンド", "라운드", " RUNDEN", " TOURS", " RONDAS", " RODADAS" } },
    { "ROUNDS", { "ROUNDS", "轮数", "回合数", "ラウンド", "라운드", "RUNDEN", "TOURS", "RONDAS", "RODADAS" } },
    { "SHORT BREAK", { "SHORT BREAK", "短休息", "短休息", "短い休憩", "짧은 휴식", "KURZE PAUSE", "PAUSE COURTE", "DESCANSO CORTO", "PAUSA CURTA" } },
    { "LONG BREAK", { "LONG BREAK", "长休息", "長休息", "長い休憩", "긴 휴식", "LANGE PAUSE", "PAUSE LONGUE", "DESCANSO LARGO", "PAUSA LONGA" } },
    { "FOCUS", { "FOCUS", "聚焦", "聚焦", "集中", "집중", "FOKUS", "FOCUS", "ENFOQUE", "FOCO" } },
    { "SHORT", { "SHORT", "短休息", "短休息", "短", "짧게", "KURZ", "COURT", "CORTO", "CURTO" } },
    { "LONG", { "LONG", "长休息", "長休息", "長", "길게", "LANG", "LONG", "LARGO", "LONGO" } },
    { "RUNNING", { "RUNNING", "运行中", "运行中", "実行中", "실행 중", "LÄUFT", "EN COURS", "EN CURSO", "EM EXECUÇÃO" } },
    { "PAUSED", { "PAUSED", "已暂停", "已暂停", "一時停止中", "일시 정지됨", "PAUSIERT", "EN PAUSE", "EN PAUSA", "PAUSADO" } },
    { "COMPLETE", { "COMPLETE", "完整", "完整", "完全版", "완전판", "KOMPLETT", "COMPLET", "COMPLETO", "COMPLETO" } },
    { "READY", { "READY", "就绪", "就绪", "準備完了", "준비됨", "BEREIT", "PRÊT", "LISTO", "PRONTO" } },
    { "START", { "START", "开始", "開始", "スタート", "시작", "START", "DÉMARRER", "INICIAR", "INICIAR" } },
    { "SETUP", { "SETUP", "设置", "設定", "設定", "설정", "EINRICHTUNG", "CONFIGURATION", "CONFIGURACIÓN", "CONFIGURAÇÃO" } },
    { "PAUSE", { "PAUSE", "暂停", "暂停", "一時停止", "일시 정지", "PAUSE", "PAUSE", "PAUSA", "PAUSAR" } },
    { "SKIP", { "SKIP", "跳过", "跳过", "スキップ", "건너뛰기", "ÜBERSPRINGEN", "PASSER", "SALTAR", "PULAR" } },
    { "RESET", { "RESET", "重置", "重置", "リセット", "재설정", "ZURÜCKSETZEN", "RÉINITIALISER", "REINICIAR", "REDEFINIR" } },
    { "RESUME", { "RESUME", "继续", "继續", "再開", "재개", "FORTSETZEN", "REPRENDRE", "REANUDAR", "CONTINUAR" } },
    { "NEXT", { "NEXT", "下一个", "下一個", "次へ", "다음", "WEITER", "SUIVANT", "SIGUIENTE", "SEGUINTE" } },
    { "TIMER NOT STARTED", { "TIMER NOT STARTED", "计时器尚未启动", "計時器尚未啟動", "タイマー未開始", "타이머가 시작되지 않음", "TIMER NICHT GESTARTET", "MINUTEUR NON DÉMARRÉ", "TEMPORIZADOR SIN INICIAR", "TIMER NÃO INICIADO" } },
    { "CHANGES NOT SAVED", { "CHANGES NOT SAVED", "更改未保存", "更改未儲存", "変更は保存されていません", "변경 사항이 저장되지 않음", "ÄNDERUNGEN NICHT GESPEICHERT", "MODIFICATIONS NON ENREGISTRÉES", "CAMBIOS SIN GUARDAR", "ALTERAÇÕES NÃO SALVAS" } },
    { "DONE", { "DONE", "完成", "完成", "完了", "완료", "FERTIG", "TERMINÉ", "HECHO", "CONCLUÍDO" } },
    { "Settings saved", { "Settings saved", "设置已保存", "設定已儲存", "設定を保存しました", "설정 저장됨", "Einstellungen gespeichert", "Réglages enregistrés", "Ajustes guardados", "Ajustes salvos" } },
};

static inline int cp_l10n_equal(const char *left, const char *right)
{
    while(*left != '\0' && *left == *right) { ++left; ++right; }
    return *left == *right;
}

static inline const char *cp_l10n_text(uint32_t language,
                                        const char *source)
{
    size_t index;

    if(language >= CP_LANGUAGE_COUNT) language = CP_LANGUAGE_ENGLISH;
    for(index = 0; index < sizeof(cp_l10n_entries) /
             sizeof(cp_l10n_entries[0]); ++index) {
        if(cp_l10n_equal(source, cp_l10n_entries[index].source))
            return cp_l10n_entries[index].values[language];
    }
    return source;
}

#endif
