#ifndef TEST_CRAZYPOD_HOME_INPUT_CONFIG_H
#define TEST_CRAZYPOD_HOME_INPUT_CONFIG_H

#define IPOD_6G
#define HAVE_CRAZYPOD_UI
#define IPOD_ACCESSORY_PROTOCOL
#define HAVE_CRAZYPOD_IAP
#define HAVE_WHEEL_ACCELERATION

#endif
