#ifndef TEST_CRAZYPOD_IAP_CONFIG_H
#define TEST_CRAZYPOD_IAP_CONFIG_H

#define IPOD_6G
#define HAVE_CRAZYPOD_UI
#define IPOD_ACCESSORY_PROTOCOL
#define HAVE_CRAZYPOD_IAP
#define CRAZYPOD_IAP_SIMPLE_REMOTE
#define HZ 100

#endif
