#ifndef CRAZYPOD_GAMEBOY_TEST_CONFIG_H
#define CRAZYPOD_GAMEBOY_TEST_CONFIG_H
#define IPOD_6G 1
#ifndef MAX_PATH
#define MAX_PATH 260
#endif
#define ROCKBOX_LITTLE_ENDIAN 1
#define HAVE_LCD_COLOR 1
#define LCD_DEPTH 16
#define LCD_WIDTH 320
#define LCD_HEIGHT 240
#define RGB565 1
#define RGB565SWAPPED 2
#define LCD_PIXELFORMAT RGB565
#endif
