#!/usr/bin/env swift

import Foundation

struct TableRange {
    let macro: String
    let symbol: String
    let first: UInt32
    let last: UInt32
}

let ranges = [
    TableRange(
        macro: "CRAZYPOD_LATIN_INITIAL",
        symbol: "crazypod_latin_initials",
        first: 0x00c0, last: 0x024f),
    TableRange(
        macro: "CRAZYPOD_CJK_EXT_A_INITIAL",
        symbol: "crazypod_cjk_ext_a_initials",
        first: 0x3400, last: 0x4dbf),
    TableRange(
        macro: "CRAZYPOD_CJK_INITIAL",
        symbol: "crazypod_cjk_initials",
        first: 0x4e00, last: 0x9fff),
    TableRange(
        macro: "CRAZYPOD_CJK_COMPAT_INITIAL",
        symbol: "crazypod_cjk_compat_initials",
        first: 0xf900, last: 0xfaff),
]

func latinInitial(_ value: UInt32) -> UInt8 {
    guard let scalar = UnicodeScalar(value) else {
        return 0
    }
    let transformed = NSMutableString(
        string: String(Character(scalar)))
    CFStringTransform(
        transformed, nil, kCFStringTransformToLatin, false)
    CFStringTransform(
        transformed, nil,
        kCFStringTransformStripCombiningMarks, false)
    for candidate in String(transformed).uppercased().utf8 {
        if candidate >= 65 && candidate <= 90 {
            return candidate
        }
        if candidate >= 128 {
            break
        }
    }
    return 0
}

func emit(_ range: TableRange, into output: inout [String]) {
    output.append(
        String(format: "#define %@_FIRST 0x%04xu",
               range.macro, range.first))
    output.append(
        String(format: "#define %@_LAST 0x%04xu",
               range.macro, range.last))
    output.append(
        "static const unsigned char \(range.symbol)[] = {")
    var line: [String] = []
    for value in range.first...range.last {
        line.append(String(format: "0x%02x", latinInitial(value)))
        if line.count == 24 {
            output.append("    " + line.joined(separator: ", ") + ",")
            line.removeAll(keepingCapacity: true)
        }
    }
    if !line.isEmpty {
        output.append("    " + line.joined(separator: ", ") + ",")
    }
    output.append("};")
    output.append("")
}

guard CommandLine.arguments.count == 2 else {
    FileHandle.standardError.write(
        Data("usage: generate-crazypod-collation.swift OUTPUT\n".utf8))
    exit(2)
}

var output = [
    "/* Generated by tools/generate-crazypod-collation.swift. */",
    "/* Values are uppercase Latin initials after system transliteration. */",
    "",
]
for range in ranges {
    emit(range, into: &output)
}
try (output.joined(separator: "\n") + "\n").write(
    toFile: CommandLine.arguments[1],
    atomically: true,
    encoding: .utf8)
