#!/usr/bin/env python3
"""Validate CrazyPod locale JSON and generate the firmware lookup table."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


LOCALES = (
    "zh-Hans", "zh-Hant", "ja", "ko", "de", "fr", "es", "pt-BR",
)
MINIAPP_SOURCES = (
    "Error", "Cannot divide by zero", "Result out of range",
    " OF ", " MIN", " ROUNDS", "ROUNDS", "SHORT BREAK", "LONG BREAK", "FOCUS",
    "SHORT", "LONG", "RUNNING", "PAUSED", "COMPLETE", "READY",
    "START", "SETUP", "PAUSE", "SKIP", "RESET", "RESUME", "NEXT",
    "TIMER NOT STARTED", "CHANGES NOT SAVED", "DONE", "Settings saved",
)
PRINTF = re.compile(
    r"%(?:\d+\$)?[-+ #0']*(?:\d+|\*)?(?:\.(?:\d+|\*))?"
    r"(?:hh|h|ll|l|j|z|t|L)?[diuoxXfFeEgGaAcspn%]"
)


def load_json(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return value


def placeholders(text: str) -> list[str]:
    return [token for token in PRINTF.findall(text) if token != "%%"]


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def validate(root: Path) -> tuple[list[str], dict[str, dict[str, str]]]:
    catalog_path = root / "catalog.json"
    catalog = load_json(catalog_path)
    strings = catalog.get("strings")
    if not isinstance(strings, dict):
        raise ValueError(f"{catalog_path}: missing object field 'strings'")

    sources = sorted(strings)
    if not sources:
        raise ValueError(f"{catalog_path}: empty catalog")
    for source, metadata in strings.items():
        if not isinstance(source, str) or not source:
            raise ValueError(f"{catalog_path}: empty/non-string source")
        if not isinstance(metadata, dict):
            raise ValueError(f"{catalog_path}: metadata for {source!r} is not an object")
        if metadata.get("keepEnglish") not in (None, True, False):
            raise ValueError(f"{catalog_path}: invalid keepEnglish for {source!r}")

    translations: dict[str, dict[str, str]] = {}
    expected = set(sources)
    for locale in LOCALES:
        path = root / f"{locale}.json"
        values = load_json(path)
        unknown = sorted(set(values) - expected)
        if unknown:
            raise ValueError(f"{path}: unknown source keys: {unknown[:5]!r}")
        translations[locale] = {}
        for source in sources:
            keep = bool(strings[source].get("keepEnglish"))
            value = values.get(source)
            if keep:
                if value not in (None, source):
                    raise ValueError(
                        f"{path}: keep-English key {source!r} must be omitted "
                        "or equal to the source"
                    )
                translations[locale][source] = source
                continue
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{path}: missing translation for {source!r}")
            if placeholders(value) != placeholders(source):
                raise ValueError(
                    f"{path}: printf placeholders differ for {source!r}: "
                    f"{placeholders(source)!r} != {placeholders(value)!r}"
                )
            translations[locale][source] = value
    return sources, translations


def generate_miniapp_header(
    output: Path, translations: dict[str, dict[str, str]],
) -> None:
    lines = [
        "/* Generated by tools/generate-crazypod-l10n.py. Do not edit. */",
        "#ifndef CRAZYPOD_MINIAPP_L10N_H",
        "#define CRAZYPOD_MINIAPP_L10N_H",
        "",
        "struct cp_l10n_entry {",
        "    const char *source;",
        "    const char *values[CP_LANGUAGE_COUNT];",
        "};",
        "",
        "static const struct cp_l10n_entry cp_l10n_entries[] = {",
    ]
    for source in MINIAPP_SOURCES:
        values = [source] + [
            translations[locale][source] for locale in LOCALES
        ]
        lines.append(
            f"    {{ {c_string(source)}, {{ "
            + ", ".join(c_string(value) for value in values)
            + " } },"
        )
    lines.extend((
        "};",
        "",
        "static inline int cp_l10n_equal(const char *left, const char *right)",
        "{",
        "    while(*left != '\\0' && *left == *right) { ++left; ++right; }",
        "    return *left == *right;",
        "}",
        "",
        "static inline const char *cp_l10n_text(uint32_t language,",
        "                                        const char *source)",
        "{",
        "    size_t index;",
        "",
        "    if(language >= CP_LANGUAGE_COUNT) language = CP_LANGUAGE_ENGLISH;",
        "    for(index = 0; index < sizeof(cp_l10n_entries) /",
        "             sizeof(cp_l10n_entries[0]); ++index) {",
        "        if(cp_l10n_equal(source, cp_l10n_entries[index].source))",
        "            return cp_l10n_entries[index].values[language];",
        "    }",
        "    return source;",
        "}",
        "",
        "#endif",
        "",
    ))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def generate(
    root: Path, output: Path, miniapp_output: Path, consumer: Path,
) -> None:
    sources, translations = validate(root)
    missing_miniapp = sorted(set(MINIAPP_SOURCES) - set(sources))
    if missing_miniapp:
        raise ValueError(
            f"catalog is missing mini-app sources: {missing_miniapp!r}"
        )
    lines = [
        "/* Generated by tools/generate-crazypod-l10n.py. Do not edit. */",
        "static const struct crazypod_l10n_entry crazypod_l10n_entries[] = {",
    ]
    for source in sources:
        values = ", ".join(
            c_string(translations[locale][source]) for locale in LOCALES
        )
        lines.append(f"    {{ {c_string(source)}, {{ {values} }} }},")
    lines.extend((
        "};",
        "",
        "#define CRAZYPOD_L10N_ENTRY_COUNT \\",
        "    ((int)(sizeof(crazypod_l10n_entries) / \\",
        "           sizeof(crazypod_l10n_entries[0])))",
        "",
    ))
    output.parent.mkdir(parents=True, exist_ok=True)
    generated_text = "\n".join(lines)
    changed = (
        not output.exists()
        or output.read_text(encoding="utf-8") != generated_text
    )
    if changed:
        output.write_text(generated_text, encoding="utf-8")
    generate_miniapp_header(miniapp_output, translations)
    if changed:
        consumer.touch()
    print(f"{output}: generated {len(sources)} complete localization entries")
    print(f"{miniapp_output}: generated {len(MINIAPP_SOURCES)} mini-app entries")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path("localization/crazypod"),
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("apps/crazypod/crazypod_l10n_data.inc"),
    )
    parser.add_argument(
        "--miniapp-output", type=Path,
        default=Path("miniapps/sdk/crazypod_miniapp_l10n.h"),
    )
    parser.add_argument(
        "--consumer", type=Path,
        default=Path("apps/crazypod/crazypod_l10n.c"),
    )
    args = parser.parse_args()
    try:
        generate(args.root, args.output, args.miniapp_output, args.consumer)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
