#!/usr/bin/env python3
"""Validate CrazyPod locale JSON and generate the firmware lookup table."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


LOCALES = (
    "zh-Hans", "zh-Hant", "ja", "ko", "de", "fr", "es", "pt-BR",
)
PRINTF = re.compile(
    r"%(?:\d+\$)?[-+ #0']*(?:\d+|\*)?(?:\.(?:\d+|\*))?"
    r"(?:hh|h|ll|l|j|z|t|L)?[diuoxXfFeEgGaAcspn%]"
)


def load_json(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return value


def placeholders(text: str) -> list[str]:
    return [token for token in PRINTF.findall(text) if token != "%%"]


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def validate(root: Path) -> tuple[list[str], dict[str, dict[str, str]]]:
    catalog_path = root / "catalog.json"
    catalog = load_json(catalog_path)
    strings = catalog.get("strings")
    if not isinstance(strings, dict):
        raise ValueError(f"{catalog_path}: missing object field 'strings'")

    sources = sorted(strings)
    if not sources:
        raise ValueError(f"{catalog_path}: empty catalog")
    for source, metadata in strings.items():
        if not isinstance(source, str) or not source:
            raise ValueError(f"{catalog_path}: empty/non-string source")
        if not isinstance(metadata, dict):
            raise ValueError(f"{catalog_path}: metadata for {source!r} is not an object")
        if metadata.get("keepEnglish") not in (None, True, False):
            raise ValueError(f"{catalog_path}: invalid keepEnglish for {source!r}")

    translations: dict[str, dict[str, str]] = {}
    expected = set(sources)
    for locale in LOCALES:
        path = root / f"{locale}.json"
        values = load_json(path)
        unknown = sorted(set(values) - expected)
        if unknown:
            raise ValueError(f"{path}: unknown source keys: {unknown[:5]!r}")
        translations[locale] = {}
        for source in sources:
            keep = bool(strings[source].get("keepEnglish"))
            value = values.get(source)
            if keep:
                if value not in (None, source):
                    raise ValueError(
                        f"{path}: keep-English key {source!r} must be omitted "
                        "or equal to the source"
                    )
                translations[locale][source] = source
                continue
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{path}: missing translation for {source!r}")
            if placeholders(value) != placeholders(source):
                raise ValueError(
                    f"{path}: printf placeholders differ for {source!r}: "
                    f"{placeholders(source)!r} != {placeholders(value)!r}"
                )
            translations[locale][source] = value
    return sources, translations


def generate(
    root: Path, output: Path, consumer: Path,
) -> None:
    sources, translations = validate(root)
    lines = [
        "/* Generated by tools/generate-crazypod-l10n.py. Do not edit. */",
        "static const struct crazypod_l10n_entry crazypod_l10n_entries[] = {",
    ]
    for source in sources:
        values = ", ".join(
            c_string(translations[locale][source]) for locale in LOCALES
        )
        lines.append(f"    {{ {c_string(source)}, {{ {values} }} }},")
    lines.extend((
        "};",
        "",
        "#define CRAZYPOD_L10N_ENTRY_COUNT \\",
        "    ((int)(sizeof(crazypod_l10n_entries) / \\",
        "           sizeof(crazypod_l10n_entries[0])))",
        "",
    ))
    output.parent.mkdir(parents=True, exist_ok=True)
    generated_text = "\n".join(lines)
    changed = (
        not output.exists()
        or output.read_text(encoding="utf-8") != generated_text
    )
    if changed:
        output.write_text(generated_text, encoding="utf-8")
    if changed:
        consumer.touch()
    print(f"{output}: generated {len(sources)} complete localization entries")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path("localization/crazypod"),
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("apps/crazypod/crazypod_l10n_data.inc"),
    )
    parser.add_argument(
        "--consumer", type=Path,
        default=Path("apps/crazypod/crazypod_l10n.c"),
    )
    args = parser.parse_args()
    try:
        generate(args.root, args.output, args.consumer)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
